# general settings
name: DCFN_X3_C64L1_FT
model_type: SRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0
# dataset and data loader settings
datasets:

  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic_X3_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 144
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod12
    dataroot_lq: datasets/Set5/LRbicx3
    io_backend:
      type: disk
      
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/GTmod12
    dataroot_lq: datasets/Set14/LRbicx3
    io_backend:
      type: disk

# network structures
network_g:
  type: REPDPFN
  in_dim: 3
  main_channels: 64
  hyper_channels: 24
  out_dim: 3
  upscale: 3

# path
path:
  pretrain_network_g: experiments/DCFN_X3_C64L1/models/net_g_800000.pth
  strict_load_g: true
  resume_state: 

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adan
    lr: !!float 5e-4
    betas: [0.98, 0.92, 0.99]
    weight_decay: !!float 5e-4
    foreach: true

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 150000, 180000, 190000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 3
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
